## TensorFlow basics

In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

1.10.1


In [5]:
hello = tf.constant("Hello ")

In [6]:
world = tf.constant("World")

In [7]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [8]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [9]:
const = tf.constant(10)

In [10]:
fill_mat = tf.fill((4,4), 10)

In [11]:
myzeros = tf.zeros((4, 4))

In [12]:
myones = tf.ones((4,4))

In [13]:
myrandn = tf.random_normal((4,4), mean=0.0, stddev=1.0, seed=None, name=None)

In [15]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [16]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [17]:
sess = tf.InteractiveSession()

In [18]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-1.9934875   0.21397552  0.18051046  1.010924  ]
 [ 0.96551496 -0.61653364  1.2264328  -1.0851033 ]
 [-1.4642464  -0.39865658  0.02377448  0.73160875]
 [-0.42461205 -0.18491292  0.0365287  -0.44269946]]


[[0.8414042  0.31731045 0.11735499 0.06403482]
 [0.5377946  0.7770958  0.8077885  0.10219395]
 [0.25661325 0.03288412 0.68132615 0.40904188]
 [0.88261807 0.90000105 0.6584288  0.28312743]]




In [19]:
a = tf.constant([[1,2],
                [3,4]])

In [20]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [22]:
b = tf.constant([[10],
               [100]])

In [23]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [24]:
result = tf.matmul(a, b)

In [25]:
sess.run(result)

array([[210],
       [430]], dtype=int32)